# Stage 1: Build frontend
FROM node:18-alpine AS builder
WORKDIR /app
COPY front/package*.json ./front/
RUN npm i --prefix ./front
COPY front ./ 
RUN npm run build --prefix ./front

# Stage 2: Serve with Nginx
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY ../deploy/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
